services:
  - type: web
    name: recruitment-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com
    autoDeploy: true
